// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: uuid.proto

package uuidpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UUID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hi uint64 `protobuf:"fixed64,1,opt,name=hi,proto3" json:"hi,omitempty"`
	Lo uint64 `protobuf:"fixed64,2,opt,name=lo,proto3" json:"lo,omitempty"`
}

func (x *UUID) Reset() {
	*x = UUID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uuid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_uuid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_uuid_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetHi() uint64 {
	if x != nil {
		return x.Hi
	}
	return 0
}

func (x *UUID) GetLo() uint64 {
	if x != nil {
		return x.Lo
	}
	return 0
}

var File_uuid_proto protoreflect.FileDescriptor

var file_uuid_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x75, 0x75, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x6e, 0x69,
	0x63, 0x68, 0x6f, 0x6c, 0x61, 0x73, 0x6e, 0x67, 0x61, 0x69, 0x2e, 0x75, 0x75, 0x69, 0x64, 0x22,
	0x26, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x69, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x06, 0x52, 0x02, 0x68, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x6c, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x06, 0x52, 0x02, 0x6c, 0x6f, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x63, 0x68, 0x6f, 0x6c, 0x61, 0x73, 0x6e, 0x67,
	0x61, 0x69, 0x2f, 0x75, 0x75, 0x69, 0x64, 0x70, 0x62, 0x2f, 0x67, 0x6f, 0x2f, 0x75, 0x75, 0x69,
	0x64, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_uuid_proto_rawDescOnce sync.Once
	file_uuid_proto_rawDescData = file_uuid_proto_rawDesc
)

func file_uuid_proto_rawDescGZIP() []byte {
	file_uuid_proto_rawDescOnce.Do(func() {
		file_uuid_proto_rawDescData = protoimpl.X.CompressGZIP(file_uuid_proto_rawDescData)
	})
	return file_uuid_proto_rawDescData
}

var file_uuid_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_uuid_proto_goTypes = []interface{}{
	(*UUID)(nil), // 0: nicholasngai.uuid.UUID
}
var file_uuid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_uuid_proto_init() }
func file_uuid_proto_init() {
	if File_uuid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_uuid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UUID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uuid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_uuid_proto_goTypes,
		DependencyIndexes: file_uuid_proto_depIdxs,
		MessageInfos:      file_uuid_proto_msgTypes,
	}.Build()
	File_uuid_proto = out.File
	file_uuid_proto_rawDesc = nil
	file_uuid_proto_goTypes = nil
	file_uuid_proto_depIdxs = nil
}
